baseURL: "https://katsuhiko-nishiyama.github.io" 
title: Katsuhiko Nishiyama
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1 
        - name: Courses
          url: courses/
          weight: 2
        - name: CV
          url: "cv.pdf"
          weight: 3

params:
    description: "This website hosts Katsu Nishiyama's research papers, course materials, curriculum vitae, and contact information."
    author: Katsuhiko Nishiyama
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Katsuhiko Nishiyama
          subtitle: "I am an Asssistant Professor at Osaka School of International Public Policy (OSIPP) of the University of Osaka. I am an **economist** working on topics related to **health**."
          imageUrl: "myphoto.jpg"
          imageWidth: 140
          imageHeight: 140
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: CV
              url: "cv.pdf"

    socialIcons:
        - name: Email
          url: katsu.nishiyama@gmail.com
        - name: Google Scholar
          url: https://scholar.google.co.jp/citations?user=L6tgPKoAAAAJ&hl=ja&oi=ao
        - name: ORCID
          url: https://orcid.org/0000-0002-8530-0314

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Katsuhiko Nishiyama"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2